WindowManager:
    StudyPeriodsWindow:
    WeekdaysWindow:
    PublicHolidaysWindow:
    ResultWindow:



<StudyPeriodsWindow>:



    name: "periods"

    MDBoxLayout:
        orientation: 'vertical'
        MDLabel:
            text: "Введите учебный период и каникулы"
            halign: 'center'
            size_hint_y: None
            height:50

        MDGridLayout:
            cols: 2

            MDRaisedButton:
                id: btn0
                text: "Выберите даты начала и окончания учебного года"
                halign: 'center'
                on_release: root.input_study_period('btn0')

            MDTextField:
                id: date1
                text: "гггг-мм-дд. - гггг-мм-дд."
                halign: 'center'




            MDRaisedButton:

                id: btn1
                text: "Выберите даты начала и окончания каникул"
                halign: 'center'
                on_release: root.input_study_period('btn1')

            MDTextField:
                id: date2
                text: "гггг-мм-дд. - гггг-мм-дд."
                halign: 'center'

            MDRaisedButton:

                id: btn2
                text: "Выберите даты начала и окончания каникул"
                halign: 'center'
                on_release: root.input_study_period('btn2')

            MDTextField:
                id: date3
                text: "гггг-мм-дд. - гггг-мм-дд."
                halign: 'center'

            MDRaisedButton:

                id: btn3
                text: "Выберите даты начала и окончания каникул"
                halign: 'center'
                on_release: root.input_study_period('btn3')

            MDTextField:
                id: date4
                text: "гггг-мм-дд. - гггг-мм-дд."
                halign: 'center'

        Button:
            text: "Вперёд"
            on_release:
                app.root.current = "weekdays"
                root.manager.transition.direction = "left"
            halign: 'center'
            size_hint_y: None
            height:50






<WeekdaysWindow>:
    name: "weekdays"
    MDBoxLayout:
        orientation: 'vertical'
        MDLabel:
            text: "Дни недели"
            halign: 'center'
            size_hint_y: None
            height:50


        MDGridLayout:
            cols: 2

            MDTextField:
                text: "Понедельник"
                halign: 'center'

            TextInput:
                id:monday_count
                text: "0"
                hint_text: "Введите количество уроков"


            MDTextField:
                text: "Вторник"
                halign: 'center'


            TextInput:
                id:tuesday_count
                text: "0"
                hint_text: "Введите количество уроков"

            MDTextField:
                text: "Среда"
                halign: 'center'

            TextInput:
                id:wednesday_count
                text: "0"
                hint_text: "Введите количество уроков"

            MDTextField:
                text: "Четверг"
                halign: 'center'

            TextInput:
                id:thursday_count
                text: "0"
                hint_text: "Введите количество уроков"

            MDTextField:
                text: "Пятница"
                halign: 'center'


            TextInput:
                id:friday_count
                text: "0"
                hint_text: "Введите количество уроков"



            MDTextField:
                text: "Суббота"
                halign: 'center'

            TextInput:
                id:saturday_count
                text: "0"
                hint_text: "Введите количество уроков"


        MDBoxLayout:
            Button:
                text: "Назад"
                on_release:
                    app.root.current = "periods"
                    root.manager.transition.direction = "right"
                halign: 'center'
                size_hint_y: None
                height:50
            Button:
                text: "Вперёд"
                on_release:
                    app.root.current = "publicHolidays"
                    root.manager.transition.direction = "left"
                halign: 'center'
                size_hint_y: None
                height:50
                on_release: root.input_working_days_of_the_week()




<PublicHolidaysWindow>:
    name: "publicHolidays"
    MDBoxLayout:
        orientation: 'vertical'
        MDLabel:
            text: "Введите праздничные дни"
            halign: 'center'
            size_hint_y: None
            height:50

        MDGridLayout:
            cols: 2

            MDRaisedButton:
                id: btn0
                text: "Ввести дату"
                halign: 'center'
                on_release: root.input_public_holidays()

            ScrollView:
            MDTextField:
                id: dates
                multiline: True
                halign: 'center'
                size_hint_y: None
                height:50


        MDBoxLayout:
            Button:
                text: "Назад"
                on_release:
                    app.root.current = "weekdays"
                    root.manager.transition.direction = "right"
                halign: 'center'
                size_hint_y: None
                height:50
            Button:
                text: "Вперёд"
                on_release:
                    app.root.current = "result"
                    root.manager.transition.direction = "left"
                halign: 'center'
                size_hint_y: None
                height:50




<ResultWindow>:
    name: "result"
    MDBoxLayout:
        orientation: 'vertical'
        MDLabel:
            text: "Даты уроков:"
            halign: 'center'
            size_hint_y: None
            height:50
        Button:
            text: "Вывод результатов"
            halign: 'center'
            size_hint_y: None
            height:50
            on_release: root.output_of_results()
        ScrollView:
            MDTextField:
                id: dates
                multiline: True
                halign: 'center'
                size_hint_y: None
                height:50

        MDBoxLayout:
            Button:
                text: "Назад"
                on_release:
                    app.root.current = "publicHolidays"
                    root.manager.transition.direction = "right"
                halign: 'center'
                size_hint_y: None
                height:50

            Button:
                text: "Сохранить"
                on_release:root.save_to_file()
                halign: 'center'
                size_hint_y: None
                height:50

            Button:
                text: "Выход"
                on_release: root.close_application()
                halign: 'center'
                size_hint_y: None
                height:50


















