WindowManager:
    StudyPeriodsWindow:
    WeekdaysWindow:
    PublicHolidaysWindow:
    ResultWindow:



<StudyPeriodsWindow>:
    id: write
    btn:[btn0, btn1, btn2, btn3]
    date1: date1
    date2: date2
    date3: date3
    date4: date4
    name: "periods"

    MDBoxLayout:
        orientation: 'vertical'
        TextInput:
            text: "Введите учебный период и каникулы"
            halign: 'center'
            size_hint_y: None
            height:50

        MDGridLayout:
            cols: 2

            MDRaisedButton:
                id: btn0
                text: "Выберите даты начала и окончания учебного года"
                halign: 'center'
                on_release: root.input_study_period('btn0')

            MDTextField:
                id: date1
                text: "гггг-мм-дд. - гггг-мм-дд."
                halign: 'center'




            MDRaisedButton:

                id: btn1
                text: "Выберите даты начала и окончания каникул"
                halign: 'center'
                on_release: root.input_study_period('btn1')

            MDTextField:
                id: date2
                text: "гггг-мм-дд. - гггг-мм-дд."
                halign: 'center'

            MDRaisedButton:

                id: btn2
                text: "Выберите даты начала и окончания каникул"
                halign: 'center'
                on_release: root.input_study_period('btn2')

            MDTextField:
                id: date3
                text: "гггг-мм-дд. - гггг-мм-дд."
                halign: 'center'

            MDRaisedButton:

                id: btn3
                text: "Выберите даты начала и окончания каникул"
                halign: 'center'
                on_release: root.input_study_period('btn3')

            MDTextField:
                id: date4
                text: "гггг-мм-дд. - гггг-мм-дд."
                halign: 'center'

        Button:
            text: "Вперёд"
            on_release:
                app.root.current = "weekdays"
                root.manager.transition.direction = "left"
            halign: 'center'
            size_hint_y: None
            height:50





<WeekdaysWindow>:
    name: "weekdays"
    MDBoxLayout:
        orientation: 'vertical'
        MDTextField:
            text: "Дни недели"
            halign: 'center'
            size_hint_y: None
            height:50


        MDGridLayout:
            cols: 2

            MDTextField:
                text: "Понедельник"
                halign: 'center'

            MDTextField:
                id:monday_count
                hint_text: "Введите количество уроков"


            MDTextField:
                text: "Вторник"
                halign: 'center'


            MDTextField:
                id:tuesday_count
                hint_text: "Введите количество уроков"

            MDTextField:
                text: "Среда"
                halign: 'center'

            MDTextField:
                id:wednesday_count
                hint_text: "Введите количество уроков"

            MDTextField:
                text: "Четверг"
                halign: 'center'

            MDTextField:
                id:thursday_count
                hint_text: "Введите количество уроков"

            MDTextField:
                text: "Пятница"
                halign: 'center'


            MDTextField:
                id:friday _count
                hint_text: "Введите количество уроков"



            MDTextField:
                text: "Суббота"
                halign: 'center'

            MDTextField:
                id:saturday _count
                hint_text: "Введите количество уроков"


        MDBoxLayout:
            Button:
                text: "Назад"
                on_release:
                    app.root.current = "periods"
                    root.manager.transition.direction = "right"
                halign: 'center'
                size_hint_y: None
                height:50
            Button:
                text: "Вперёд"
                on_release:
                    app.root.current = "publicHolidays"
                    root.manager.transition.direction = "left"
                halign: 'center'
                size_hint_y: None
                height:50









<PublicHolidaysWindow>:
    name: "publicHolidays"
    MDBoxLayout:
        orientation: 'vertical'
        MDTextField:
            text: "Праздники"
            halign: 'center'



        MDBoxLayout:
            Button:
                text: "Назад"
                on_release:
                    app.root.current = "weekdays"
                    root.manager.transition.direction = "right"
                halign: 'center'
                size_hint_y: None
                height:50
            Button:
                text: "Вперёд"
                on_release:
                    app.root.current = "result"
                    root.manager.transition.direction = "left"
                halign: 'center'
                size_hint_y: None
                height:50



<ResultWindow>:
    name: "result"
    MDBoxLayout:
        orientation: 'vertical'
        MDTextField:
            text: "Даты уроков:"
            halign: 'center'
            size_hint_y: None
            height:50

        MDTextField:

        MDBoxLayout:
            Button:
                text: "Назад"
                on_release:
                    app.root.current = "publicHolidays"
                    root.manager.transition.direction = "right"
                halign: 'center'
                size_hint_y: None
                height:50
            Button:
                text: "Вперёд"
                on_release:
                    app.root.current = "result"
                    root.manager.transition.direction = "left"
                halign: 'center'
                size_hint_y: None
                height:50


















